### ISSUE TITLE
Text does not appear to be smoothed

### ISSUE THREAD

**Issue by nmur** [fBosch/vscode-text-clarity#1]
Apologies as this is quite a vague issue and I don't have any diagnostics to show, but I don't see any change to the smoothing in VSCode version 1.11.2, using Text Clarity 1.0.1.

I can see the new additions to index.html after installing (although I had to run VSCode in administrator mode first).

**Comment by fbosch** [comment]
The purpose of the extension is to disable the smoothing (anti-aliasing) of the editor pane; this is to allow for usage of bitmap fonts that do not require any form of anti-aliasing (such as Terminus TTF)

The name of the extension might be a bit misleading, I see that now.
