### ISSUE TITLE
Doesn't seem to work with VSCode 1.14.0

### ISSUE THREAD

**Issue by mulderns** [fBosch/vscode-text-clarity#2]
After upgrading to VS Code 1.14.0, text is anti-aliased again.

**Comment by fbosch** [comment]
Alright, it stopped working once I updated as well.

I will investigate why _soon_ and keep you updated here till I have a fix.

**Comment by mulderns** [comment]
As a workaround I modify in dev mode the #workbench.editors.files.textFileEditor 
 -> -webkit-font-smoothing: none;

**Comment by fbosch** [comment]
That is basically what happened automatically before, it seems like they have upped security a bit; I'm not able to modify source files from an extension anymore. I'll let you know if I find a way somehow.

**Comment by Qonsyuma** [comment]
Even though it would be nice to have as an extensions again, now I can't even manage to get rid of the smoothing manually, any way to do it manually you know? :/
